---
name: Catalyst-Plugin-Unicode-Encoding
version: 0.2
author:
  - 'Christian Hansen, C<ch@ngmedia.com>'
abstract: Unicode aware Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.2
  Encode: 2.1
provides:
  Catalyst::Plugin::Unicode::Encoding:
    file: lib/Catalyst/Plugin/Unicode/Encoding.pm
    version: 0.2
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
